### PR TITLE
[patch] MongoDB version fix

### PR DESCRIPTION
**Pull request by racree**
Remove MongoDB community dependency on the ibm catalog version.  Instead dynamically lookup the installed catalog version or fallback to the default MongoDB version.

### CODE REVIEW

**Comment by racree** [comment]
Verified mongo deployed using the mascli command "mas install"

```
TASK [ibm.mas_devops.mongodb : Catalog Version] ********************************
Tuesday 12 September 2023  20:58:54 +0000 (0:00:00.028)       0:00:02.907 ***** 
ok: [localhost] => {
    "msg": [
        "Catalog Version ............................ v8-230725-amd64"
    ]
}

TASK [ibm.mas_devops.mongodb : Load CASE bundle versions] **********************
Tuesday 12 September 2023  20:58:54 +0000 (0:00:00.051)       0:00:02.958 ***** 
ok: [localhost] => {"ansible_facts": {"appconnect_version": "6.2.0", "catalog_digest": "sha256:f0776894d5b584bfdd10c3de2f5e586ddafdaca9b247d13ef05dc23fe98cfe2a", "common_svcs_version": "1.19.2", "couchdb_version": "1.0.13", "cp4d_platform_version": "2.8.0+20230417.110116", "db2u_extras_version": "1.0.1", "db2u_version": "5.1.1", "dd_version": "1.1.4", "elasticsearch_version": "1.1.1336", "events_version": "4.6.0", "mas_assist_version": {"8.10.x": "8.7.1", "8.9.x": "8.6.4"}, "mas_core_version": {"8.10.x": "8.10.3", "8.9.x": "8.9.8"}, "mas_hputilities_version": {"8.10.x": "8.6.1", "8.9.x": "8.5.1"}, "mas_iot_version": {"8.10.x": "8.7.3", "8.9.x": "8.6.8"}, "mas_manage_version": {"8.10.x": "8.6.3", "8.9.x": "8.5.7"}, "mas_monitor_version": {"8.10.x": "8.10.4", "8.9.x": "8.9.6"}, "mas_optimizer_version": {"8.10.x": "8.4.1", "8.9.x": "8.3.3"}, "mas_predict_version": {"8.10.x": "8.8.2", "8.9.x": "8.7.2"}, "mas_visualinspection_version": {"8.10.x": "8.8.1", "8.9.x": "8.7.1"}, "model_train_version": "1.2.5", "mongo_extras_version": "4.4.21", "sls_version": "3.7.0", "spark_version": "6.4.0", "tsm_version": "1.5.0", "uds_extras_version": "1.3.0", "uds_version": "2.0.11", "wd_extras_version": "1.0.0", "wd_version": "5.3.0", "wml_version": "6.4.0", "wsl_version": "6.4.0"}, "ansible_included_var_files": ["/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/common_vars/casebundles/v8-230725-amd64.yml"], "changed": false}

TASK [ibm.mas_devops.mongodb : Set mongo version to default value when no catalog] ***
Tuesday 12 September 2023  20:58:55 +0000 (0:00:00.048)       0:00:03.007 ***** 
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ibm.mas_devops.mongodb : Mongo Version] **********************************
Tuesday 12 September 2023  20:58:55 +0000 (0:00:00.027)       0:00:03.034 ***** 
ok: [localhost] => {
    "msg": [
        "Mongo Version ............................ 4.4.21"
    ]
}
```
```
PLAY RECAP *********************************************************************
localhost                  : ok=54   changed=16   unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
```

**Comment by racree** [comment]
Verified mongdb role passes when `MAS_CATALOG_VERSION` not set.

```
TASK [ibm.mas_devops.mongodb : Catalog Version] ************************************************************************************************************************************************************************
Tuesday 12 September 2023  21:48:18 +0000 (0:00:00.032)       0:00:03.347 ***** 
ok: [localhost] => {
    "msg": [
        "Catalog Version ............................ v8-230725-amd64"
    ]
}

TASK [ibm.mas_devops.mongodb : Load CASE bundle versions] **************************************************************************************************************************************************************
Tuesday 12 September 2023  21:48:18 +0000 (0:00:00.062)       0:00:03.410 ***** 
ok: [localhost] => {"ansible_facts": {"appconnect_version": "6.2.0", "catalog_digest": "sha256:f0776894d5b584bfdd10c3de2f5e586ddafdaca9b247d13ef05dc23fe98cfe2a", "common_svcs_version": "1.19.2", "couchdb_version": "1.0.13", "cp4d_platform_version": "2.8.0+20230417.110116", "db2u_extras_version": "1.0.1", "db2u_version": "5.1.1", "dd_version": "1.1.4", "elasticsearch_version": "1.1.1336", "events_version": "4.6.0", "mas_assist_version": {"8.10.x": "8.7.1", "8.9.x": "8.6.4"}, "mas_core_version": {"8.10.x": "8.10.3", "8.9.x": "8.9.8"}, "mas_hputilities_version": {"8.10.x": "8.6.1", "8.9.x": "8.5.1"}, "mas_iot_version": {"8.10.x": "8.7.3", "8.9.x": "8.6.8"}, "mas_manage_version": {"8.10.x": "8.6.3", "8.9.x": "8.5.7"}, "mas_monitor_version": {"8.10.x": "8.10.4", "8.9.x": "8.9.6"}, "mas_optimizer_version": {"8.10.x": "8.4.1", "8.9.x": "8.3.3"}, "mas_predict_version": {"8.10.x": "8.8.2", "8.9.x": "8.7.2"}, "mas_visualinspection_version": {"8.10.x": "8.8.1", "8.9.x": "8.7.1"}, "model_train_version": "1.2.5", "mongo_extras_version": "4.4.21", "sls_version": "3.7.0", "spark_version": "6.4.0", "tsm_version": "1.5.0", "uds_extras_version": "1.3.0", "uds_version": "2.0.11", "wd_extras_version": "1.0.0", "wd_version": "5.3.0", "wml_version": "6.4.0", "wsl_version": "6.4.0"}, "ansible_included_var_files": ["/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/common_vars/casebundles/v8-230725-amd64.yml"], "changed": false}

TASK [ibm.mas_devops.mongodb : Set mongo version to default value when no catalog] *************************************************************************************************************************************
Tuesday 12 September 2023  21:48:18 +0000 (0:00:00.068)       0:00:03.478 ***** 
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ibm.mas_devops.mongodb : Mongo Version] **************************************************************************************************************************************************************************
Tuesday 12 September 2023  21:48:18 +0000 (0:00:00.031)       0:00:03.510 ***** 
ok: [localhost] => {
    "msg": [
        "Mongo Version ............................ 4.4.21"
    ]
}

```

**Comment by racree** [comment]
Use default when catalog not found
```TASK [ibm.mas_devops.mongodb : Lookup ibm-operator-catalog] ********************
Wednesday 13 September 2023  19:40:46 +0000 (0:00:00.083)       0:00:02.403 *** 
ok: [localhost] => {"api_found": true, "changed": false, "resources": []}

TASK [ibm.mas_devops.mongodb : set_fact] ***************************************
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.729)       0:00:03.133 *** 
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ibm.mas_devops.mongodb : Catalog Version] ********************************
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.036)       0:00:03.170 *** 
skipping: [localhost] => {}

TASK [ibm.mas_devops.mongodb : Load CASE bundle versions] **********************
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.030)       0:00:03.200 *** 
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ibm.mas_devops.mongodb : Set mongo version to default value when no catalog] ***
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.023)       0:00:03.224 *** 
ok: [localhost] => {"ansible_facts": {"mongo_extras_version": "4.4.21"}, "changed": false}

TASK [ibm.mas_devops.mongodb : Mongo Version] **********************************
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.034)       0:00:03.259 *** 
ok: [localhost] => {
    "msg": [
        "Mongo Version ............................ 4.4.21"
    ]
}

TASK [ibm.mas_devops.mongodb : Load mongo defaults] ****************************
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.030)       0:00:03.289 *** 
ok: [localhost] => {"ansible_facts": {"extra_images": [{"digest": "sha256:2d5339dab49c3b9523ca97b53580db0f3a291a671a60f5882c5ed18a66073520", "name": "ibmmas/mongodb-kubernetes-operator", "registry": "quay.io", "tag": "0.7.9"}, {"digest": "sha256:5c1483fa22cfb772f186a30180fcfa4af91ff3a638b28a37cc9f997f8ac046f9", "name": "mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook", "registry": "quay.io", "tag": "1.0.6"}, {"digest": "sha256:00dc01552af1eac8a457d7214ae4f913dd2a14409c0125dead25808e40cc0d62", "name": "mongodb/mongodb-agent", "registry": "quay.io", "tag": "12.0.15.7646-1"}, {"digest": "sha256:419924de6a1bee566a4fb92656c6be79b0adf36a875a2845699f64e3b536186e", "name": "mongodb/mongodb-kubernetes-readinessprobe", "registry": "quay.io", "tag": "1.0.13"}, {"digest": "sha256:e1b43604ed1b54804f15c421de666e8be6c6d1ebf57e5825dff22493f9bd5f1e", "name": "ibmmas/mongo", "registry": "quay.io", "tag": "4.4.21"}]}, "ansible_included_var_files": ["/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/mirror_extras_prepare/vars/mongoce_4.4.21.yml"], "changed": false}

TASK [ibm.mas_devops.mongodb : Retrieve image setting parts] *******************
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.034)       0:00:03.324 *** 
ok: [localhost] => {"ansible_facts": {"mongodb_agent_image_digest": "sha256:00dc01552af1eac8a457d7214ae4f913dd2a14409c0125dead25808e40cc0d62", "mongodb_agent_image_name": "mongodb/mongodb-agent", "mongodb_agent_image_registry": "quay.io", "mongodb_image_digest": "sha256:e1b43604ed1b54804f15c421de666e8be6c6d1ebf57e5825dff22493f9bd5f1e", "mongodb_image_name": "ibmmas/mongo", "mongodb_image_registry": "quay.io", "mongodb_operator_image_digest": "sha256:2d5339dab49c3b9523ca97b53580db0f3a291a671a60f5882c5ed18a66073520", "mongodb_operator_image_name": "ibmmas/mongodb-kubernetes-operator", "mongodb_operator_image_registry": "quay.io", "mongodb_operator_image_tag": "0.7.9", "mongodb_operator_version_upgrade_post_start_hook_image_digest": "sha256:5c1483fa22cfb772f186a30180fcfa4af91ff3a638b28a37cc9f997f8ac046f9", "mongodb_operator_version_upgrade_post_start_hook_image_name": "mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook", "mongodb_operator_version_upgrade_post_start_hook_image_registry": "quay.io", "mongodb_readinessprobe_image_digest": "sha256:419924de6a1bee566a4fb92656c6be79b0adf36a875a2845699f64e3b536186e", "mongodb_readinessprobe_image_name": "mongodb/mongodb-kubernetes-readinessprobe", "mongodb_readinessprobe_image_registry": "quay.io"}, "changed": false}

TASK [ibm.mas_devops.mongodb : Construct image full image settings] ************
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.074)       0:00:03.399 *** 
ok: [localhost] => {"ansible_facts": {"mongodb_ce_version": "0.7.9", "target_mongodb_agent_image": "quay.io/mongodb/mongodb-agent@sha256:00dc01552af1eac8a457d7214ae4f913dd2a14409c0125dead25808e40cc0d62", "target_mongodb_image": "quay.io/ibmmas/mongo@sha256:e1b43604ed1b54804f15c421de666e8be6c6d1ebf57e5825dff22493f9bd5f1e", "target_mongodb_operator_image": "quay.io/ibmmas/mongodb-kubernetes-operator@sha256:2d5339dab49c3b9523ca97b53580db0f3a291a671a60f5882c5ed18a66073520", "target_mongodb_operator_version_upgrade_post_start_hook_image": "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook@sha256:5c1483fa22cfb772f186a30180fcfa4af91ff3a638b28a37cc9f997f8ac046f9", "target_mongodb_readinessprobe_image": "quay.io/mongodb/mongodb-kubernetes-readinessprobe@sha256:419924de6a1bee566a4fb92656c6be79b0adf36a875a2845699f64e3b536186e", "target_mongodb_version": "4.4.21"}, "changed": false}

TASK [ibm.mas_devops.mongodb : community : install : Debug properties] *********
Wednesday 13 September 2023  19:40:47 +0000 (0:00:00.032)       0:00:03.431 *** 
ok: [localhost] => {
    "msg": [
        "MongoDb namespace ............ mongoce",
        "MongoDb operator version ..... 0.7.9",
        "MongoDb data capacity ........ 20Gi",
        "MongoDb logs capacity ........ 20Gi",
        "MongoDb replicas ............. 3",
        "MongoDb version .............. 4.4.21",
        "MAS instance ID .............. rka",
        "MAS config directory ......... /workspace/configs",
        "Controlled Upgrade ........... False"
    ]
}

**Comment by racree** [comment]
mongodb role sets mongo version to default value when either operator catalog does not exist or does not contain a the mongo version, such as when MAS_CATALOG_VERSION=v8-manage-amd64

```
TASK [ibm.mas_devops.mongodb : include_tasks] **************************************************************************************************************************************************************************
Thursday 14 September 2023  15:57:10 +0000 (0:00:00.038)       0:00:02.351 **** 
included: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/mongodb/tasks/providers/community/install.yml for localhost

TASK [ibm.mas_devops.mongodb : Lookup ibm-operator-catalog] ************************************************************************************************************************************************************
Thursday 14 September 2023  15:57:10 +0000 (0:00:00.101)       0:00:02.452 **** 
ok: [localhost] => {"api_found": true, "changed": false, "resources": []}

TASK [ibm.mas_devops.mongodb : set_fact] *******************************************************************************************************************************************************************************
Thursday 14 September 2023  15:57:11 +0000 (0:00:00.743)       0:00:03.196 **** 
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ibm.mas_devops.mongodb : Catalog Version] ************************************************************************************************************************************************************************
Thursday 14 September 2023  15:57:11 +0000 (0:00:00.044)       0:00:03.240 **** 
skipping: [localhost] => {}

TASK [ibm.mas_devops.mongodb : Load CASE bundle versions] **************************************************************************************************************************************************************
Thursday 14 September 2023  15:57:11 +0000 (0:00:00.040)       0:00:03.281 **** 
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ibm.mas_devops.mongodb : Set mongo version to default value when no catalog] *************************************************************************************************************************************
Thursday 14 September 2023  15:57:11 +0000 (0:00:00.032)       0:00:03.313 **** 
ok: [localhost] => {"ansible_facts": {"mongo_extras_version": "4.4.21"}, "changed": false}

TASK [ibm.mas_devops.mongodb : Mongo Version] **************************************************************************************************************************************************************************
Thursday 14 September 2023  15:57:11 +0000 (0:00:00.042)       0:00:03.356 **** 
ok: [localhost] => {
    "msg": [
        "Mongo Version ............................ 4.4.21"
    ]
}
```

**Review by whitfiea — APPROVED** [review]

**Pull request merged**
