### PR TITLE
[minor] Complete support for user workload monitoring in OCP

### PR DESCRIPTION
**Pull request by alequint**
This PR includes:

- An ansible role capable of install Grafana Operator, configure cluster to extend monitoring for user-defined metrics and connect Grafana Dashboards developed by application teams with prometheus metrics as data source
- An ansible playbook to install grafana, for teams that have already an environment setup but no Grafana (e.g. MAS Managed Service customers)
- Addition of grafana role call as part of masdeps playbook, so that when pipeline tasks are used to install masdeps, grafana will also be installed.
- Updates in Devops Collection public documentation explaining use of grafana role and playbooks

### CODE REVIEW

**Comment by stonepd** [comment]
@alequint - Is this one ready to merge? It looks like you have made the change requested by @durera to remove the `startingCSV`, if so could you remove the `TODO:` in the [main.yaml](https://github.com/ibm-mas/ansible-devops/blob/alefq-grafana-support/ibm/mas_devops/roles/ocp_setup_monitoring/tasks/main.yaml) and I'll merge this PR

**Comment by alequint** [comment]
@stonepd not ready yet, I need to review the latest changes from @durera. It is on my todo list 👍

**Comment by alequint** [comment]
> # shouldn't be using starting CSV in a subscription, a future update to
> # the catalog may mask that CSV and break the automation at any point in time
> # so starting CSV should not be used.

@durera just to close this topic, I see other playbooks using startingcsv as a constant in the role's defaults or even hard coded inside it (see `amq streams` [here](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/amqstreams/templates/subscription.yml.j2#L27)). In this playbook/role I tried to make it parameterized to avoid repack the collection because of that in future.

**Comment by durera** [comment]
Can we get this caught up with master and ready to merge?  Moving to draft state until this is ready to be looked at again.

**Comment by durera** [comment]
Discussed in Slack today, this work is not in progress anymore so closing this PR.

**Pull request closed without merging**
