### PR TITLE
[major] Migrate airgap support into ibm.mas_airgap collection

### PR DESCRIPTION
**Pull request by stonepd**
Remove airgap specific playbooks and roles, these will be included in a new ansible-airgap repository. 
A number of airgap specifics still need to be supported within these roles, such as the SBO installation in a disconnected environment.

### CODE REVIEW

**Review by tomklapiscak — CHANGES_REQUESTED** [review]
`suite_install` still installs the airgap catalog: https://github.com/ibm-mas/ansible-devops/blob/e2aa20b829005d1875ade493e129a645c83f8166/ibm/mas_devops/roles/suite_install/tasks/main.yml#L48.

**Review by tomklapiscak — CHANGES_REQUESTED** [review]
ibm/mas_devops/roles/ocp_setup_mas_deps/templates/certificate-manager-airgap/cert-manager.yaml should have `.yml` file extension according to contribution guidelines (I think!).

Although all the other templates in the `ocp_setup_mas_deps` use the `.yaml` extension. Perhaps an exception has been made here? If so, leave be. If not, ideally all the templates would be renamed to have `.yml` extension.

**Review by tomklapiscak — CHANGES_REQUESTED** [review]
Remove airgap support section from lite-core-quickburn playbook docs:

https://github.com/ibm-mas/ansible-devops/blob/e2aa20b829005d1875ade493e129a645c83f8166/docs/playbooks/lite-core-quickburn.md?plain=1#L99-L100

**Review by tomklapiscak — CHANGES_REQUESTED** [review]
As per contribution guidelines, tasks that are not in main.yaml of the role should be prefixed with an indentifier for the file that they are part of so that the Ansible logs guide the user to the appropriate part of the role.

- All task names in ibm/mas_devops/roles/ocp_setup_mas_deps/tasks/sbo/install_airgap.yml should be prefixed with `sbo/install_airgap : `

- All task names in ibm/mas_devops/roles/ocp_setup_mas_deps/tasks/sbo/install_connected.yml should be prefixed with `sbo/install_connected : `

**Comment by tomklapiscak** [comment]
That's all my review comments so far. 

I've merged in everything from master (only a single merge conflict seen and it was straightforward to resolve).

I've checked that contribution guidelines have been adhered to, looked for any remaining airgap stuff that missed during its removal (other than the stuff that is still needed as per the PR description), and I've done some basic sanity checks (e.g. no typos in var names, no remaining references to deleted files/roles). 

However, this is the first time I've encountered anything to do with airgap support, so I'm not able to confirm with confidence that the actual logic here is 100% correct. Depending on how confident you are of these changes and how extensively they've been tested, it might be worth getting someone with a bit more knowledge in this area to take a look too.

**Comment by stonepd** [comment]
Thanks for the review Tom, I've made the requested updates. I won't publish yet though, I need to wait for @durera to return before publishing, so we can get the compatible ansible-airgap repo published as well.

**Review by durera — APPROVED** [review]
Merged master into the branch, changes look good to me otherwise

**Comment by stonepd** [comment]
@durera - the latest merge looks OK to me, please proceed with releasing the PR

**Pull request merged**
